### ISSUE TITLE
fix null pointer when attached to apple TV

### ISSUE THREAD

**Issue by amymcgovern** [amymcgovern/spacesettlers#10]
Window size isn't calculated right when attached to the Apple TV (causes a null pointer error).  Fix this.

**Comment by amymcgovern** [comment]
[java] Exception in thread "main" java.lang.NullPointerException
     [java] 	at java.awt.Window.init(Window.java:497)
     [java] 	at java.awt.Window.<init>(Window.java:537)
     [java] 	at java.awt.Frame.<init>(Frame.java:420)
     [java] 	at javax.swing.JFrame.<init>(JFrame.java:233)
     [java] 	at spacesettlers.gui.SpaceSettlersGUI.<init>(SpaceSettlersGUI.java:69)
     [java] 	at spacesettlers.simulator.SpaceSettlersSimulator.createGUI(SpaceSettlersSimulator.java:203)
     [java] 	at spacesettlers.simulator.SpaceSettlersSimulator.<init>(SpaceSettlersSimulator.java:151)
     [java] 	at spacesettlers.simulator.RunSimulator.main(RunSimulator.java:105)

**Comment by amymcgovern** [comment]
This seems to be a bug inside java 8 itself.  It is reported by many others that java won't create frames when connected to an airplay device.  Since it is not an issue in my code, nothing to fix for now.
